# Day 18 of 100 Days of Machine Learning

# NumPy Exercises 

In [1]:
#import numpy
import numpy as np

1. Create 1D numpy array

In [2]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

2. Create 3x3 array

In [3]:
array = np.arange(9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create 3x3 boolean array

In [4]:
array = np.full((3,3), True, dtype=bool)
array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. Extract all even numbers from 1D array

In [5]:
#array of 0 to 9 numbers
array = np.arange(10)
array[array%2 == 0]

array([0, 2, 4, 6, 8])

In [6]:
# random numbers array added by me :)
array = np.array([0,2,3,4,5,7,6,10,9,7,8])
array[array%2==0]

array([ 0,  2,  4,  6, 10,  8])

5. Replace all even numbers with 1

In [7]:
array = np.arange(10)
array[array%2 == 0] = 1

In [8]:
array

array([1, 1, 1, 3, 1, 5, 1, 7, 1, 9])

6. Replace all even number with 1 wihtout affecting original array

In [9]:
array = np.arange(10)
array1 = np.where(array % 2 == 1, 1, array)
print(array)
print(array1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 1 4 1 6 1 8 1]


7. Reshape 1D array to 2D array

In [10]:
array1D = np.arange(10)
array2D = array1D.reshape(2,5)

In [11]:
array2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
array2D.shape

(2, 5)

8. Reshape 1D to 2D array without mentioning column size

In [13]:
array1D = np.arange(10)
array2D = array1D.reshape(2, -1)
# -1 automatically decides the number of cols

In [14]:
array2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

9. Stack two array vertically.

In [15]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)

In [16]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
c = np.vstack([a,b])

In [19]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

10. Stack two array horizontally.

In [20]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)

In [21]:
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
c = np.hstack([a,b])
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
