# Day 17 of #100DaysOfMLCode

# NumPy | Linear Algebra | Part 3

In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
y = np.random.randn(4,3)
y

array([[-0.24279655, -0.6439226 ,  1.80723102],
       [ 0.26189815,  1.17118874,  0.14558193],
       [ 0.3837158 , -1.57089666,  0.36550174],
       [ 0.59776209, -0.69883783, -2.18704463]])

In [4]:
x.dot(y)

array([[  3.82319548,  -5.8095864 ,  -5.55327844],
       [  7.82551341, -12.77945977,  -5.02819824]])

In [5]:
np.dot(x,y)

array([[  3.82319548,  -5.8095864 ,  -5.55327844],
       [  7.82551341, -12.77945977,  -5.02819824]])

In [6]:
np.dot(x, np.ones(4))

array([10., 26.])

In [7]:
# @ symbol also use for matrix multiplication in Python
x @ y

array([[  3.82319548,  -5.8095864 ,  -5.55327844],
       [  7.82551341, -12.77945977,  -5.02819824]])

In [8]:
X = np.random.randn(5,5)

#### numpy linear algebra function

In [9]:
import numpy.linalg as linalg

In [10]:
X = np.random.randn(3,3)
X

array([[-2.11886491,  1.45584321, -0.39511481],
       [ 0.00665065, -0.50211801,  1.74412662],
       [ 1.69166881, -0.07796014, -1.29580095]])

In [11]:
# inverse matrix
linalg.inv(X)

array([[0.3411412 , 0.83149111, 1.0151527 ],
       [1.28330732, 1.48060108, 1.60155928],
       [0.36815154, 0.99643368, 0.45720323]])

In [12]:
# eigen values
linalg.eig(X)

(array([-2.13002789+1.47655833j, -2.13002789-1.47655833j,
         0.34327191+0.j        ]),
 array([[-0.32148245+0.52431229j, -0.32148245-0.52431229j,
         -0.4199466 +0.j        ],
        [-0.36154936-0.33007708j, -0.36154936+0.33007708j,
         -0.81729815+0.j        ],
        [ 0.61812364+0.j        ,  0.61812364-0.j        ,
         -0.39454859+0.j        ]]))

In [13]:
# compute svd (singular value decomposition)
linalg.svd(X)

(array([[-0.80951824, -0.38857704, -0.4401001 ],
        [-0.02356099,  0.77052188, -0.63697795],
        [ 0.58662177, -0.50527608, -0.63290678]]),
 array([3.00535164, 2.33803837, 0.32815756]),
 array([[ 0.90088388, -0.40342512, -0.16017618],
        [-0.01124578, -0.39058759,  0.92049708],
        [-0.43391447, -0.82745967, -0.35641089]]))

In [14]:
# compute matrix determinant
linalg.det(X)

2.3058409142947873

In [15]:
# return diagonal of square matrix as 1D array
X.diagonal()

array([-2.11886491, -0.50211801, -1.29580095])