# Day 15 of #100DaysOfMLCode

# NumPy Part 2

In [1]:
import numpy as np

In [2]:
array = np.arange(12).reshape((3,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Transposing arrays

In [3]:
array.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#### Universal Functions

In [4]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
# square root of array
np.sqrt(array)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [6]:
# compute expontent of each element $e^x$
np.exp(array)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [7]:
# compute square of each elements
np.square(array)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [8]:
# compute sign of each element ( +ve (1) , -ve(-1) or zero(0))
np.sign(array)

array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
#check whether array is finite(isfinite) or infinite(isinf)
np.isfinite(array)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
#check whether array is finite(isfinite) or infinite(isinf)
np.isinf(array)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

#### statistical functions

you can apply on two array or single array.

In [11]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
#add
np.add(array,2)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [13]:
#subtract
np.subtract(array,3)

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [14]:
#multiply
np.multiply(array, 3)

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [15]:
# divide
np.divide(array, 3)

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667]])

In [16]:
#floor_divide -- truncate the reminder
np.floor_divide(array,3)

array([[0, 0, 0, 1],
       [1, 1, 2, 2],
       [2, 3, 3, 3]])

In [17]:
# greater, greater_equal, less, less_equal, equal, not_equal are methods as name suggest 
# which return boolen array
np.greater(array, 3)

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [18]:
np.greater_equal(array, 3)

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#### Conditional logic as array operations

In [19]:
array > 2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
np.where(array > 2, 4, 2) # it will replace value > 2 to 4 and < 2 to 2

array([[2, 2, 2, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

#### mathematical and statistical methods

In [21]:
arr = np.random.randn(3,4)
arr

array([[-0.770696  , -0.88743739, -1.98408954,  0.0555214 ],
       [-0.38941803, -0.84492981, -0.18109299, -2.06090159],
       [-0.47938023, -1.06636696,  0.86409914,  0.75876126]])

In [22]:
arr.mean()

-0.582160897070909

In [23]:
# other way is 
np.mean(arr)

-0.582160897070909

In [24]:
arr.sum()

-6.985930764850908

In [25]:
arr.mean(axis=0) # mean of each columns

array([-0.54649809, -0.93291139, -0.43369447, -0.41553964])

In [26]:
arr.mean(axis=1) # mean of each row

array([-0.89667538, -0.86908561,  0.0192783 ])

In [27]:
arr.argmin() # return index of min element

7

In [28]:
arr.argmax() # return index of max element

10

In [29]:
arr.std() # standard deviation

0.8703097336588835

In [30]:
arr.var() # variance of array

0.7574390325013969

In [31]:
arr.sort() # sort arraay. works rowwise.
arr

array([[-1.98408954, -0.88743739, -0.770696  ,  0.0555214 ],
       [-2.06090159, -0.84492981, -0.38941803, -0.18109299],
       [-1.06636696, -0.47938023,  0.75876126,  0.86409914]])

In [32]:
one_d = np.random.randn(5)
one_d

array([-0.58256171, -0.00453606, -0.29465887, -1.73485768, -0.13875548])

In [33]:
one_d.sort()
one_d

array([-1.73485768, -0.58256171, -0.29465887, -0.13875548, -0.00453606])

In [34]:
(one_d > 0).sum() #sum of positive values

0

#### Array set operations

In [35]:
names = np.array(['Durgesh', 'Python', 'Machine', 'Python', 'Durgesh', 'Java'])
names

array(['Durgesh', 'Python', 'Machine', 'Python', 'Durgesh', 'Java'],
      dtype='<U7')

In [36]:
np.unique(names)

array(['Durgesh', 'Java', 'Machine', 'Python'], dtype='<U7')

In [37]:
x = np.array([1, 4, 6, 2, 8, 6, 4])
x

array([1, 4, 6, 2, 8, 6, 4])

In [38]:
y = np.array([1, 3, 2, 6, 5, 7, 6, 3])
y

array([1, 3, 2, 6, 5, 7, 6, 3])

In [39]:
np.unique(x)

array([1, 2, 4, 6, 8])

In [40]:
np.intersect1d(x,y)

array([1, 2, 6])

In [41]:
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
np.setdiff1d(x,y)

array([4, 8])